dist: xenial
language: python
sudo: false
cache:
  directories:
    - $HOME/.cache/pip
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8-dev"
  - "pypy3"

install:
  # Ensure modern pip/etc to avoid some issues w/ older worker environs
  - pip install pytest
  - pip install coverage
  - pip install pytest-cov
  - pip install mock
  - pip install codecov # For codecov specifically
  - pip install .

script:
  - cd tests
  - pytest --cov=wait_for_it_to
  - cd $TRAVIS_BUILD_DIR


env:
  - CODECOV_TOKEN="919258c7-ed4b-463f-973a-68fc7a081d2d"

after_success:
  - codecov

deploy:
  provider: pypi
  user: studioj
  password: $PYPI_PASS
  distributions: "sdist bdist_wheel"
  on:
    branch: master
    tags: true
    python: 3.7
  repo: studioj/wait_for_it

