dist: xenial
language: python
sudo: false
cache:
  directories:
    - $HOME/.cache/pip
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8-dev"
  - "pypy3"

install:
  # Ensure modern pip/etc to avoid some issues w/ older worker environs
  - pip install pytest
  - pip install coverage
  - pip install pytest-cov
  - pip install mock
  - pip install codecov # For codecov specifically
  - pip install .

script:
  - cd tests
  - pytest --cov=wait_for_it_to
  - cd $TRAVIS_BUILD_DIR


env:
  - CODECOV_TOKEN="919258c7-ed4b-463f-973a-68fc7a081d2d"

after_success:
  - codecov

deploy:
  provider: pypi
  user: studioj
  distributions: sdist
  password:
    secure: HvOHZYNolZnwmy7wA9FfxyTlzLYwwkrwUoNqqfrvlBdVAsPnipJtdkcO67Vysfsy5Pa+bMSFvM8olTEN5lOasqsbxT3AB17SMLl3VyC8ZRgqOxV0CK4fi7yo+iUBP9zZz5ZWK1mLKkdddYoLezOaUuWXL7UN/jNadom2zLn94LT2Vn3rJuGJvs6m2eOPM4w0m2dk0XIjTy9teRCMMbMT9Q+Ciovzt7cZB+qi34TL/LR3ck7x9QurEHUV/A+ZXSJIAe+ER+adl3YlvUZiOoSeDoMSQl1bZ7cFQ9RehbNuX0X+Iv/Qe/MwKvmjjUhynj4mwSY5Dbo8PjQ7cRZZw8ahLyIDRNgLYmq85ZhVUzMrllQdeE8Qtuo9+btfvzW8et+Tg3OXuuFUbhpg0hwApEu1i+ugTzPXEi4E/m+5/5LBYgtQGTGTINdNYr9Dncu/S1YNyqYFKxLXLHkCVpno/Yqhh3gLmkXK8zzNkfMo4VSlmugqB9GVOrG94hM8gMunvrnDJQw121fXrvuQvOSHoB1DhcYdfka8yCYlBUO0nmRqf+/qnjOIoR6dMgKvlE+/0mez/LuJSwJWf3+1f2QH5pfCqindpJZZB2XN2tsl99ZkGhbCom4knk/ZuF0oC49+X3AGgfrQEilriNIjmq1vh8FUrA9r/gV5TfR+2+8SAegp0vk=
  on:
    branch: master
    tags: true
    python: 3.7
  repo: studioj/wait_for_it

