dist: xenial
language: python
sudo: false
cache:
  directories:
    - $HOME/.cache/pip
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8-dev"
  - "pypy3"

install:
  # Ensure modern pip/etc to avoid some issues w/ older worker environs
  - pip install pytest
  - pip install coverage
  - pip install pytest-cov
  - pip install mock
  - pip install codecov # For codecov specifically
  - pip install .

script:
  - cd tests
  - pytest --cov=wait_for_it_to
  - cd $TRAVIS_BUILD_DIR


env:
  - CODECOV_TOKEN="919258c7-ed4b-463f-973a-68fc7a081d2d"

after_success:
  - codecov

deploy:
  provider: pypi
  user: studioj
  distributions: sdist
  password:
    secure: U6RZoxVrzakjSwAeFwgkLGTGhuUxS26OXJ3YiWIlhdSmKQJmcjDOjHbH/OQ7YkdSeci0YkyQD7CdbLDPwutYvfK0IHBvbkC6eQFmbfE3b/8v2rEXSi1ndgAinXAx0Ai23XzA13DxPBjjRNioATIHggKuzC7bE1KCu6f11sy0emBW+qhGuamOQx3dDoXjjYDlmnOg+x01Ut9MCFSqEe6IJlfq6CzhaRwiOH19MmPbYDliYeqDyg0NT1vCzFNMAmgFyJilCKtLjMBYi9NgXyLXEx5+hXJ5uPsoYZ+kMVIEqb59ch5gL7d5xSigrD9Zued5bj6w8HigZasZYLJwe+oaGtc+ZZ8PgId11uIozF2ybIE1nMvpzdIpr0E17BDuki5nt83rCztEw1vNoLHo7rLn2myzd6Nob5axX91n00Ujsxhz77rPmWDLMFUTgdi1Q7/iJrot2duwLnd4dOmTkw1KRaKXSDJlYWkw7aymz1OZmDM1aosccvdwggTXBXcv2moEbLGnNpUW+udCJxR/rjPCWi9zCUtJFabUO8P/6u/I52IbUYBri70YL/tuVrTPxKeLpyhId5hwMjpH9kFr/QtsGy48UilTm1kaxKIiw+mP6z4Ko4FNnjCz9fwaVHyH00+RL2ebINWElGUmDMqVE3BtS5U8+TxTJ9b78/6Lz8H3yug=
  on:
    branch: master
    tags: true
    python: 3.7
  repo: studioj/wait_for_it

